#!/usr/bin/env bash
#If 9, say Hi!
doittilitchanges=1
while [ $doittilitchanges -ne 11 ]
do
        if [ $doittilitchanges -eq 9 ]; then
                echo "hi"

        else
                echo "Best School"
        fi
    ((doittilitchanges++))
done

