#!/usr/bin/env bash
#If 9, say Hi!
doittilitchanges=1
while [ $doittilitchanges -ne 12 ]
do
        if [ $doittilitchanges -eq 10 ]; then
                echo "Hi"

        else
                echo "Best School"
        fi
    ((doittilitchanges++))
done

