#!/usr/bin/env bash
#If 9, say Hi!
doittilitchanges=1
while [ $doittilitchanges -ne 11 ]
do
        if [ $doittilitchanges -eq 4 ]; then
                echo "bad luck"
		
	elif	[ $doittilitchanges -eq 8 ]; then
		echo "good luck"	
	else
                echo "Best School"
        fi
    ((doittilitchanges++))
done
