#!/usr/bin/env bash
#file checking for exists, regular and empty

checker=school
if [ -e $checker ]; then
    echo "school file exists"
else
    echo "school file does not exist"
    exit 1
fi
if [ ! -s $checker ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -f $checker ]; then
    echo "school is a regular file"
fi
