#!/usr/bin/env bash
# Manages the program called manage_my_process

FILE="/var/run/my_process.pid"

create()
{
    sudo touch $FILE
    sudo bash -c "echo $$ > $FILE"
}

if [ "$1" == "start" ]; then
	create 	
	./manage_my_process &
	echo "manage_my_process started"

elif [ "$1" == "stop" ]
	then
#		kill "$(cat /var/run/my_process.pid)"
#               rm /var/run/my_process.pid
#               echo "manage_my_process stopped"

		[ -e "$FILE" ] && sudo pkill -p "$FILE" && sudo rm "$FILE" 

		echo "manage_my_process stpped"

elif [ "$1" == "restart" ]
	then
#		kill "$(cat /var/run/my_process.pid)"
#    		rm /var/run/my_process.pid
#    		echo "manage_my_process stopped"

                [ -e "$FILE" ] && sudo pkill -p "$FILE" && sudo rm "$FILE"
		Create
		echo "manage_my_process restarted"
		#$0 stop >& /dev/null
    		#$0 start >& /dev/null
       				
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
