#!/usr/bin/env bash
# Manages the program called manage_my_process

FILE="/var/run/my_process.pid"

create()
{
    sudo touch $FILE
    sudo bash -c "echo $! > $FILE"
}

if [ "$1" == "start" ]; then
	create 	
	./manage_my_process &
	echo "manage_my_process started"

elif [ "$1" == "stop" ]; then
        [ -e "$FILE" ] && sudo pkill -p "$(cat "$FILE")" && sudo rm "$FILE"
        echo "manage_my_process stopped"

#		kill "$(cat /var/run/my_process.pid)"
#               rm /var/run/my_process.pid
#               echo "manage_my_process stopped"

elif [ "$1" == "restart" ]; then
        [ -e "$FILE" ] && sudo pkill -p "$(cat "$FILE")" && sudo rm "$FILE"
        create
   	echo "manage_my_process restarted"

#               kill "$(cat /var/run/my_process.pid)"
#               rm /var/run/my_process.pid
#               echo "manage_my_process stopped"
else

	echo "Usage: manage_my_process {start|stop|restart}"
fi
