#!/usr/bin/env bash
# Manages the program called manage_my_process

FILE="/var/run/my_process.pid"

create()

{
    ./manage_my_process &
    echo $! | sudo tee $FILE > /dev/null
}

if [ "$1" == "start" ]; then
    create
    echo "manage_my_process started"

elif [ "$1" == "stop" ]; then
    if [ -f "$FILE" ]; then
        sudo kill "$(cat "$FILE")" && sudo rm "$FILE"
        echo "manage_my_process stopped"
    else
        echo "PID file does not exist. Is the process running?"
    fi

elif [ "$1" == "restart" ]; then
    if [ -f "$FILE" ]; then
        sudo kill "$(cat "$FILE")" && sudo rm "$FILE"
        create
        echo "manage_my_process restarted"
    else
        echo "No process is running to restart. Starting it now."
        create
        echo "manage_my_process started"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi







#{
#    sudo touch $FILE
#    sudo bash -c "echo $! > $FILE"
#}

#if [ "$1" == "start" ]; then
#	create 	
#	./manage_my_process &
#	echo "manage_my_process started"

#elif [ "$1" == "stop" ]; then
#         [ -e "$FILE" ] && sudo pkill -p "$(cat "$FILE")" && sudo rm "$FILE"
#        echo "manage_my_process stopped"

#		kill "$(cat /var/run/my_process.pid)"
#               rm /var/run/my_process.pid
#               echo "manage_my_process stopped"

#elif [ "$1" == "restart" ]; then
#        [ -e "$FILE" ] && sudo pkill -p "$(cat "$FILE")" && sudo rm "$FILE"
#        create
#   	echo "manage_my_process restarted"

#               kill "$(cat /var/run/my_process.pid)"
#               rm /var/run/my_process.pid
#               echo "manage_my_process stopped"
#else

#	echo "Usage: manage_my_process {start|stop|restart}"
#fi
